/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as LocatorRouteImport } from './routes/locator'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as AboutAwardsRouteImport } from './routes/about.awards'
import { Route as AboutStoryRouteImport } from './routes/about.story'
import { Route as AboutSustainabilityRouteImport } from './routes/about.sustainability'
import { Route as AccountSignInRouteImport } from './routes/account.sign-in'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const LocatorRoute = LocatorRouteImport.update({
  id: '/locator',
  path: '/locator',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAwardsRoute = AboutAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AboutRoute,
} as any)
const AboutStoryRoute = AboutStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AboutRoute,
} as any)
const AboutSustainabilityRoute = AboutSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => AboutRoute,
} as any)
const AccountSignInRoute = AccountSignInRouteImport.update({
  id: '/account/sign-in',
  path: '/account/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/delivery': typeof DeliveryRoute
  '/ethics': typeof EthicsRoute
  '/experience': typeof ExperienceRoute
  '/locator': typeof LocatorRoute
  '/shop': typeof ShopRoute
  '/trade': typeof TradeRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/story': typeof AboutStoryRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/delivery': typeof DeliveryRoute
  '/ethics': typeof EthicsRoute
  '/experience': typeof ExperienceRoute
  '/locator': typeof LocatorRoute
  '/shop': typeof ShopRoute
  '/trade': typeof TradeRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/story': typeof AboutStoryRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/delivery': typeof DeliveryRoute
  '/ethics': typeof EthicsRoute
  '/experience': typeof ExperienceRoute
  '/locator': typeof LocatorRoute
  '/shop': typeof ShopRoute
  '/trade': typeof TradeRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/story': typeof AboutStoryRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/corporate'
    | '/delivery'
    | '/ethics'
    | '/experience'
    | '/locator'
    | '/shop'
    | '/trade'
    | '/about/awards'
    | '/about/story'
    | '/about/sustainability'
    | '/account/sign-in'
    | '/collections/$handle'
    | '/products/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/corporate'
    | '/delivery'
    | '/ethics'
    | '/experience'
    | '/locator'
    | '/shop'
    | '/trade'
    | '/about/awards'
    | '/about/story'
    | '/about/sustainability'
    | '/account/sign-in'
    | '/collections/$handle'
    | '/products/$handle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/corporate'
    | '/delivery'
    | '/ethics'
    | '/experience'
    | '/locator'
    | '/shop'
    | '/trade'
    | '/about/awards'
    | '/about/story'
    | '/about/sustainability'
    | '/account/sign-in'
    | '/collections/$handle'
    | '/products/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  DeliveryRoute: typeof DeliveryRoute
  EthicsRoute: typeof EthicsRoute
  ExperienceRoute: typeof ExperienceRoute
  LocatorRoute: typeof LocatorRoute
  ShopRoute: typeof ShopRoute
  TradeRoute: typeof TradeRoute
  AccountSignInRoute: typeof AccountSignInRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locator': {
      id: '/locator'
      path: '/locator'
      fullPath: '/locator'
      preLoaderRoute: typeof LocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/awards': {
      id: '/about/awards'
      path: '/awards'
      fullPath: '/about/awards'
      preLoaderRoute: typeof AboutAwardsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/story': {
      id: '/about/story'
      path: '/story'
      fullPath: '/about/story'
      preLoaderRoute: typeof AboutStoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/sustainability': {
      id: '/about/sustainability'
      path: '/sustainability'
      fullPath: '/about/sustainability'
      preLoaderRoute: typeof AboutSustainabilityRouteImport
      parentRoute: typeof AboutRoute
    }
    '/account/sign-in': {
      id: '/account/sign-in'
      path: '/account/sign-in'
      fullPath: '/account/sign-in'
      preLoaderRoute: typeof AccountSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutAwardsRoute: typeof AboutAwardsRoute
  AboutStoryRoute: typeof AboutStoryRoute
  AboutSustainabilityRoute: typeof AboutSustainabilityRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAwardsRoute: AboutAwardsRoute,
  AboutStoryRoute: AboutStoryRoute,
  AboutSustainabilityRoute: AboutSustainabilityRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  DeliveryRoute: DeliveryRoute,
  EthicsRoute: EthicsRoute,
  ExperienceRoute: ExperienceRoute,
  LocatorRoute: LocatorRoute,
  ShopRoute: ShopRoute,
  TradeRoute: TradeRoute,
  AccountSignInRoute: AccountSignInRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  ProductsHandleRoute: ProductsHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
